### ISSUE TITLE
User Authentication

### ISSUE THREAD

**Issue by ChukwuemekaOkobi** [ChukwuemekaOkobi/Google-pixel_Art_Solution#1]
Describe tasks of user authentications

**Comment by ChukwuemekaOkobi** [comment]
- [ ]  Complete OOAD 
- [ ]  Design UI 
- [ ]  Build API endpoints 
- [ ]  Added Unit Test
- [ ]  Done Code Review 
- [ ]  Done Sprint Review 
- [ ]  Deployed
